name: Minify Lua

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install luamin
        run: npm install -g luamin

      - name: Minify Lua files
        run: |
          mkdir -p minified
          find src -name "*.lua" -exec luamin {} -o minified/{} \;

      - name: Artifact minified files
        uses: actions/upload-artifact@v2
        with:
          name: minified-lua
          path: minified
