name: Minify Lua

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install luamin
        run: npm install -g luamin

      - name: Allow Execution
        run: chmod +x .github/scripts/*.sh
      - name: Debug Stuff
        run: .github/scripts/debug.sh
      - name: Minify Lua files
        run: .github/scripts/minify.sh

      - name: Artifact minified files
        uses: actions/upload-artifact@v2
        with:
          name: minified-lua
          path: minified
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
      - name: Deploy to server
        run: |
          scp -i $SSH_KEY_PATH -r minified/* $SSH_USER@$SSH_HOST:$SSH_PATH/minified/
          scp -i $SSH_KEY_PATH -r src/* $SSH_USER@$SSH_HOST:$SSH_PATH/unminified/src/
        shell: bash
        env:
          SSH_USER: ${{secrets.SSH_USER}}
          SSH_HOST: ${{secrets.SSH_HOST}}
          SSH_PATH: ${{secrets.SSH_PATH}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key