name: Minify Lua

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install luamin
        run: npm install -g luamin

      - name: Allow Execution
        run: chmod +x .github/scripts/*.sh
      - name: Debug Stuff
        run: .github/scripts/debug.sh
      - name: Minify Lua files
        run: .github/scripts/minify.sh

      - name: Artifact minified files
        uses: actions/upload-artifact@v2
        with:
          name: minified-lua
          path: minified
